# Generated by Django 4.2.1 on 2023-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('patch', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'app_config_version',
                'db_table_comment': '앱 버전 구분 모델',
                'ordering': ['-updated_at'],
            },
        ),
    ]
