# Generated by Django 4.2.1 on 2023-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
