# Generated by Django 4.2.1 on 2024-02-03 17:42

from django.db import migrations, models
import django.db.models.deletion
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_occupancyrateupdatelog_congestion'),
        ('challenge', '0003_challenge_url'),
        ('notification', '0004_pushnotification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=31, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=notification.models.pop_up_image_upload_path)),
                ('web_view_url', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, default=None, max_length=255, null=True)),
                ('in_app_route_target', models.IntegerField(blank=True, choices=[(0, '지도'), (1, '활동'), (2, '챌린지'), (3, '마이페이지'), (4, '카카오톡채널')], default=None, null=True)),
                ('cafe', models.ForeignKey(blank=True, db_column='cafe', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_up_notification', to='cafe.cafe')),
                ('challenge', models.ForeignKey(blank=True, db_column='challenge', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_up_notification', to='challenge.challenge')),
            ],
            options={
                'db_table': 'notification_pop_up_notification',
                'db_table_comment': '팝업 모델',
                'ordering': ['-datetime'],
            },
        ),
    ]
