# Generated by Django 4.2.1 on 2024-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_popupnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupnotification',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
