# Generated by Django 4.2.1 on 2023-09-12 16:52

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('brand_csv_file', models.FileField(upload_to=data.models.brand_csv_upload_path)),
            ],
            options={
                'db_table': 'data_brand_data_update',
                'db_table_comment': '브랜드정보 업데이트하는 admin전용 모델',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='CongestionAreaDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('congestion_area_csv_file', models.FileField(upload_to=data.models.congestion_area_csv_upload_path)),
            ],
            options={
                'db_table': 'data_congestion_area_data_update',
                'db_table_comment': '혼잡도 제공 해주는 지역 정보 업데이트하는 admin전용 모델',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='CongestionDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_congestion_data_update',
                'db_table_comment': '지역 실시간 혼잡도 업데이트하는 admin전용 모델',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='DistrictDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=15)),
                ('gu_dong_csv_file', models.FileField(upload_to=data.models.district_csv_upload_path)),
            ],
            options={
                'db_table': 'data_district_data_update',
                'db_table_comment': '지역정보 업데이트하는 admin전용 모델',
                'ordering': ['-last_update', 'city'],
            },
        ),
        migrations.CreateModel(
            name='ItemDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_item_data_update',
                'db_table_comment': '아이템, 브랜드 업데이트하는 admin전용 모델',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='NicknameAdjectiveDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('adjective_csv_file', models.FileField(upload_to=data.models.nickname_adjective_csv_upload_path)),
            ],
            options={
                'db_table': 'data_nickname_adjective_data_update',
                'db_table_comment': '닉네임 자동생성 후보 형용사 업데이트',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='NicknameNounDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('noun_csv_file', models.FileField(upload_to=data.models.nickname_noun_csv_upload_path)),
            ],
            options={
                'db_table': 'data_nickname_noun_data_update',
                'db_table_comment': '닉네임 자동생성 후보 명사 업데이트',
                'ordering': ['-last_update'],
            },
        ),
    ]
