# Generated by Django 4.2.1 on 2023-09-20 13:05

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeDataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=15)),
                ('dong', models.CharField(max_length=15)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('cafe_csv_file', models.FileField(upload_to=data.models.cafe_csv_upload_path)),
            ],
            options={
                'db_table': 'data_cafe_data_update',
                'db_table_comment': '새로운 카페를 추가하고 정보 업데이트',
                'ordering': ['-last_update'],
            },
        ),
    ]
