# Generated by Django 4.2.1 on 2023-09-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_cafedataupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafePointUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_cafe_point_update',
                'db_table_comment': '각 카페의 좌표에 따라 point값 지정',
                'ordering': ['-last_update'],
            },
        ),
    ]
