# Generated by Django 4.2.1 on 2023-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_cafepointupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOpeningUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_cafe_opening_update',
                'db_table_comment': '카페 영업시간 정보에 따라 영업중인지 여부 업데이트',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='OccupancyPredictionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_occupancy_prediction_update',
                'db_table_comment': '카페 예상 혼잡도 저장',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHoursUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_opening_hours_update',
                'db_table_comment': '카페 영업시간 정보의 string으로부터 time을 추출해 저장',
                'ordering': ['-last_update'],
            },
        ),
    ]
