# Generated by Django 4.2.1 on 2023-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_cafeopeningupdate_occupancypredictionupdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_leader_update',
                'db_table_comment': '랭킹정보 업데이트',
                'ordering': ['-last_update'],
            },
        ),
    ]
