# Generated by Django 4.2.1 on 2023-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_leaderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyRegistrationChallengeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_occupancy_registration_challenge_update',
                'db_table_comment': '혼잡도 등록 챌린지 정산',
                'ordering': ['-last_update'],
            },
        ),
    ]
