# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0001_initial'),
        ('cafe_log', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeksharingranker',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='week_sharing_ranker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totalsharingranker',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='total_sharing_ranker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthsharingranker',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='month_sharing_ranker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyhotcafelog',
            name='cafe_log',
            field=models.OneToOneField(blank=True, db_column='cafe_log', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_hot_cafe_log', to='cafe_log.cafelog'),
        ),
    ]
