# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to=shop.models.coupon_image_upload_path)),
            ],
            options={
                'db_table': 'shop_coupon',
                'db_table_comment': '쿠폰 모델',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gifticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.gifticon_image_upload_path)),
                ('tr_id', models.CharField(max_length=31)),
                ('expiration_period', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shop_gifticon',
                'db_table_comment': '기프티콘 모델',
                'ordering': ['expiration_period'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=31, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('small_image_url', models.URLField(max_length=255)),
                ('large_image_url', models.URLField(max_length=255)),
                ('limit_day', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'shop_item',
                'db_table_comment': '아이템 모델',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_period', models.DateTimeField(blank=True, default=None, null=True)),
                ('coupon', models.ForeignKey(db_column='coupon', on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to='shop.coupon')),
            ],
            options={
                'db_table': 'shop_user_coupon',
                'db_table_comment': '유저에게 배포된 쿠폰',
                'ordering': ['expiration_period', 'user__username'],
            },
        ),
    ]
