# Generated by Django 4.2.1 on 2023-09-12 16:52

import cafe_log.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('카공/업무', '카공/업무'), ('만남', '만남'), ('힐링', '힐링'), ('자유', '자유')])),
                ('content', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_log_cafe_log',
                'db_table_comment': '카페로그 모델',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeLogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cafe_log_like',
                'db_table_comment': '카페로그 좋아요 모델',
                'ordering': ['-cafe_log__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('카공/업무', '카공/업무'), ('만남', '만남'), ('힐링', '힐링'), ('자유', '자유')])),
                ('image', models.ImageField(upload_to=cafe_log.models.snapshot_image_upload_path)),
            ],
            options={
                'db_table': 'cafe_log_snapshot',
                'db_table_comment': '카페로그 속 사진 모델',
            },
        ),
        migrations.CreateModel(
            name='CafeLogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('cafe_log', models.ForeignKey(db_column='cafe_log', on_delete=django.db.models.deletion.CASCADE, related_name='cafe_log_report', to='cafe_log.cafelog')),
            ],
            options={
                'db_table': 'cafe_log_cafe_log_report',
                'db_table_comment': '카페로그 신고 모델',
                'ordering': ['-cafe_log__created_at'],
            },
        ),
    ]
