# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'request_cafe_addition_request',
                'db_table_comment': '카페 등록 요청',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeInformationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, default=None, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'request_cafe_information_suggestion',
                'db_table_comment': '카페 추가 정보 등록 요청',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMigrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=8)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_migration_request',
                'db_table_comment': '사용자 정보이전 요청',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('카페', '카페'), ('혼잡도', '혼잡도'), ('앱사용', '앱사용'), ('디자인', '디자인'), ('기타', '기타')], max_length=63)),
            ],
            options={
                'db_table': 'request_withdrawal_request',
                'db_table_comment': '회원탈퇴 요청',
                'ordering': ['-requested_at'],
            },
        ),
    ]
