# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0001_initial'),
        ('cafe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermigrationrequest',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_migration_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='cafe',
            field=models.ForeignKey(blank=True, db_column='cafe', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_information_suggestion', to='cafe.cafe'),
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='suggested_cafe',
            field=models.ForeignKey(blank=True, db_column='suggested_cafe', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_cafe_information_suggestion', to='cafe.cafe'),
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='suggested_new_image',
            field=models.ForeignKey(blank=True, db_column='suggested_new_image', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_information_suggestion', to='cafe.cafeimage'),
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='cafe_information_suggestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeadditionrequest',
            name='cafe',
            field=models.ForeignKey(blank=True, db_column='cafe', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_addition_request', to='cafe.cafe'),
        ),
        migrations.AddField(
            model_name='cafeadditionrequest',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='cafe_addition_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
