# Generated by Django 4.2.1 on 2023-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeadditionrequest',
            name='etc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
