# Generated by Django 4.2.1 on 2023-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_cafeadditionrequest_etc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeinformationsuggestion',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='cafeinformationsuggestion',
            name='suggested_new_image',
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cafeinformationsuggestion',
            name='etc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
