# Generated by Django 4.2.1 on 2024-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_appfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appfeedback',
            name='reason',
        ),
        migrations.AddField(
            model_name='appfeedback',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
