# Generated by Django 4.2.1 on 2024-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_remove_appfeedback_reason_appfeedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeadditionrequest',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
