# Generated by Django 4.2.1 on 2023-09-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengepoint',
            name='challenger',
            field=models.ForeignKey(db_column='challenger', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_point', to='challenge.challenger'),
        ),
        migrations.AddField(
            model_name='challengemilestone',
            name='challenge',
            field=models.ForeignKey(db_column='challenge', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_milestone', to='challenge.challenge'),
        ),
    ]
