# Generated by Django 4.2.1 on 2024-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
