# Generated by Django 4.2.1 on 2024-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_occupancy_registration_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
