# Generated by Django 4.2.1 on 2023-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cati_delete_cafetypetag'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cati_acidity',
            field=models.IntegerField(choices=[(-2, '매우 씁쓸함'), (-1, '씁쓸함'), (1, '산미가 있음'), (2, '산미가 강함')], default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='cati_coffee',
            field=models.IntegerField(choices=[(-2, '음료가 매우 맛있음'), (-1, '음료가 맛있음'), (1, '커피가 맛있음'), (2, '커피가 매우 맛있음')], default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='cati_openness',
            field=models.IntegerField(choices=[(-2, '매우 아늑함'), (-1, '아늑함'), (1, '개방적임'), (2, '매우 개방적임')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='cati_workspace',
            field=models.IntegerField(choices=[(-2, '매우 감성적임'), (-1, '감성적임'), (1, '업무하기 좋음'), (2, '매우 업무하기 좋음')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_cafe',
            field=models.ManyToManyField(blank=True, db_column='favorite_cafe', related_name='profile', to='cafe.cafe'),
        ),
    ]
