# Generated by Django 4.2.1 on 2023-09-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0003_remove_cafetypetag_is_work_friendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.IntegerField(choices=[(-2, '매우 아늑함'), (-1, '아늑함'), (0, '보통'), (1, '개방적임'), (2, '매우 개방적임')])),
                ('coffee', models.IntegerField(choices=[(-2, '음료가 매우 맛있음'), (-1, '음료가 맛있음'), (0, '보통'), (1, '커피가 맛있음'), (2, '커피가 매우 맛있음')])),
                ('workspace', models.IntegerField(choices=[(-2, '매우 감성적임'), (-1, '감성적임'), (0, '보통'), (1, '업무하기 좋음'), (2, '매우 업무하기 좋음')])),
                ('acidity', models.IntegerField(choices=[(-2, '매우 씁쓸함'), (-1, '씁쓸함'), (0, '보통'), (1, '산미가 있음'), (2, '산미가 강함')])),
                ('cafe', models.ForeignKey(db_column='cafe', on_delete=django.db.models.deletion.CASCADE, related_name='cati', to='cafe.cafe')),
                ('user', models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cafe_cati',
                'db_table_comment': 'CATI 구분을 위한 type tag 모델',
                'ordering': ['cafe__name'],
            },
        ),
        migrations.DeleteModel(
            name='CafeTypeTag',
        ),
    ]
