# Generated by Django 4.2.1 on 2023-09-24 22:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_cafe_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), null=True, srid=4326),
        ),
    ]
