# Generated by Django 4.2.1 on 2023-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_location_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='fri_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='fri_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='mon_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='mon_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='sat_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='sat_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='sun_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='sun_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='thu_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='thu_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='tue_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='tue_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='wed_closing_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='wed_opening_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
