# Generated by Django 4.2.1 on 2023-10-24 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_openinghour_fri_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='occupancyrateupdatelog',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
