# Generated by Django 4.2.1 on 2023-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_occupancyrateupdatelog_is_google_map_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancyrateupdatelog',
            name='congestion',
            field=models.CharField(blank=True, choices=[('여유', '여유'), ('보통', '보통'), ('약간 붐빔', '약간 붐빔'), ('붐빔', '붐빔')], default=None, null=True),
        ),
    ]
